### ISSUE TITLE
[osx] build failing with most recent OSX/XCode on scrypt-hash (nan related)

### ISSUE THREAD

**Issue by jrgm** [dannycoates/scrypt-hash#7]
As noted in https://github.com/mozilla/fxa-auth-server/issues/909, builds are failing on uptodate `osx+npm+nodejs@0.10`. Naively updating to nan@1.7.0 seems to "fix" the problem.

**Comment by dannycoates** [comment]
I can reproduce. It looks like nan [1.5.2](https://github.com/rvagg/nan/blob/master/CHANGELOG.md#152-jan-23-2015) fixed the issue. I'll update nan to latest and push a patch release
