### ISSUE TITLE
nan changes are needed for iojs 3.0

### ISSUE THREAD

**Issue by jrgm** [dannycoates/scrypt-hash#8]
See https://travis-ci.org/jrgm/scrypt-hash/jobs/74868118

You probably knew this already, but the build fails on iojs 3.0 due to v8 and nan changes. I did an update to nan 2.0.4 and ran the tool in node_modules/nan/tools/1to2.js but still had failures. Tried fixing some obvious API changes, but eventually gave up due to "not having a real clue"(TM).

**Comment by vladikoff** [comment]
Also node v4

**Comment by dannycoates** [comment]
fixed in 1.1.13

**Comment by vladikoff** [comment]
Amazingg!!! :star:
